baseURL = "https://thennext.com/"
languageCode = "en-us"
title = "ThenNext"
author = "Wouter Lindenhof"
theme = "contrast-hugo"

[permalinks]
  posts = "/:year/:month/:title/"

[params]
  minimal = false
  excerpts = true
  description = "my blog"