baseURL = "https://thennext.com/"
languageCode = "en-us"
title = "ThenNext"
author = "Wouter Lindenhof"
theme = "contrast-hugo"


[params]
  minimal = false
  excerpts = true
  description = "my blog"